// <auto-generated />
using System;
using KodtestMio.DbModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KodtestMio.Migrations
{
    [DbContext(typeof(RetailDbContext))]
    [Migration("20240227153904_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KodtestMio.DbModel.EntityModels.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KodtestMio.DbModel.EntityModels.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("KodtestMio.DbModel.EntityModels.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "imageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,3)")
                        .HasAnnotation("Relational:JsonPropertyName", "price");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "stock");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Soffbord i svartbetsat lackerat askfaner med en hylla för smart och praktiskt förvaring.",
                            ImageUrl = "/images/products/11255.jpg0",
                            Name = "Yesterday Soffbord, L 130 cm",
                            Price = 2795m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tavellist för dina tavlor och posters. Välj mellan oljad massiv ek, lackerad ljus björk, svart eller vitlackerad mdf.\r\n",
                            ImageUrl = "/images/products/106501.jpg",
                            Name = "Living Tavellist, B 120 cm",
                            Price = 199m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tavellist för dina tavlor och posters. Välj mellan oljad massiv ek, lackerad ljus björk, svart eller vitlackerad mdf.",
                            ImageUrl = "/images/products/16240.jpg0",
                            Name = "Living Tavellist, B 80 cm",
                            Price = 149m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vägghylla i vitlackerad mdf med två hyllplan. Enkel att montera och varje hyllplan har en maxbelastning på fem kg vardera.",
                            ImageUrl = "/images/products/16289.jpg",
                            Name = "Living Vägghylla, H 60 cm",
                            Price = 199m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vägghylla i vitlackerad mdf med fyra hyllplan. Hyllan är enkel att montera och varje hyllplan har en maxbelastning på fem kg.",
                            ImageUrl = "/images/products/16290.jpg",
                            Name = "Living Vägghylla, H 100 cm",
                            Price = 299m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 6,
                            Description = "Med sin följsamma och omfamnande känsla blir Dream en självklar favorit i många år framöver. Det som skapar den mysiga känslan är en X-pocketresår i samarbete med en 5-zons pocketresår i den övre resårkärnan. Sängens övre pocketresår ger en helt individuell avlastning vilket minskar risken för tryck som gör att du vaknar och X-pocketresåren ger madrassen en extra ytmjuk känsla som bidrar till den omfamnande känslan. För en extra stabilitet i sängen har vi lagt till en kantförstärkning i övre resårkärnan. Den undre resårkärnan har en pocketresår som gör att du får ett extra djup i sängen och mycket god följsamhet. Sängen är svensktillverkad och finns i tre olika komforter, medium, fast eller extra fast. I priset ingår bäddmadrass Sense Delux och metallben.",
                            ImageUrl = "/images/products/c64b5527-307a-4e9b-a5be-d0805f6b99b4_0f7.jpg",
                            Name = "Dream Delux Ramsäng, enkelsäng med bäddmadrass Sense Delux",
                            Price = 10495m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 7,
                            Description = "Med sin följsamma och omfamnande känsla blir Dream en självklar favorit i många år framöver. Det som skapar den mysiga känslan är en X-pocketresår i samarbete med en 5-zons pocketresår i den övre resårkärnan. Sängens övre pocketresår ger en helt individuell avlastning vilket minskar risken för tryck som gör att du vaknar och X-pocketresåren ger madrassen en extra ytmjuk känsla som bidrar till den omfamnande känslan. För en extra stabilitet i sängen har vi lagt till en kantförstärkning i övre resårkärnan. Den undre resårkärnan har en pocketresår som gör att du får ett extra djup i sängen och mycket god följsamhet. Sängen är svensktillverkad och finns i tre olika komforter, medium, fast eller extra fast. I priset ingår bäddmadrass Sense Delux och metallben.",
                            ImageUrl = "/images/products/c64b5527-307a-4e9b-a5be-d0805f6b99b4_0f7.jpg",
                            Name = "Dream Delux Ramsäng, enkelsäng med bäddmadrass Sense Delux",
                            Price = 10495m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 8,
                            Description = "Med sin följsamma och omfamnande känsla blir Dream en självklar favorit i många år framöver. Det som skapar den mysiga känslan är en X-pocketresår i samarbete med en 5-zons pocketresår i den övre resårkärnan. Sängens övre pocketresår ger en helt individuell avlastning vilket minskar risken för tryck som gör att du vaknar och X-pocketresåren ger madrassen en extra ytmjuk känsla som bidrar till den omfamnande känslan. För en extra stabilitet i sängen har vi lagt till en kantförstärkning i övre resårkärnan. Den undre resårkärnan har en pocketresår som gör att du får ett extra djup i sängen och mycket god följsamhet. Sängen är svensktillverkad och finns i tre olika komforter, medium, fast eller extra fast. I priset ingår bäddmadrass Sense Delux och metallben.",
                            ImageUrl = "/images/products/be42c2c5-bc3c-4c14-a959-e100bdb9eeab_188.jpg",
                            Name = "Dream Delux Ramsäng, enkelsäng med bäddmadrass Sense Delux",
                            Price = 10495m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 9,
                            Description = "Med sin följsamma och omfamnande känsla blir Dream en självklar favorit i många år framöver. Det som skapar den mysiga känslan är en X-pocketresår i samarbete med en 5-zons pocketresår i den övre resårkärnan. Sängens övre pocketresår ger en helt individuell avlastning vilket minskar risken för tryck som gör att du vaknar och X-pocketresåren ger madrassen en extra ytmjuk känsla som bidrar till den omfamnande känslan. För en extra stabilitet i sängen har vi lagt till en kantförstärkning i övre resårkärnan. Den undre resårkärnan har en pocketresår som gör att du får ett extra djup i sängen och mycket god följsamhet. Sängen är svensktillverkad och finns i tre olika komforter, medium, fast eller extra fast. I priset ingår bäddmadrass Sense Delux och metallben.",
                            ImageUrl = "/images/products/c64b5527-307a-4e9b-a5be-d0805f6b99b4_0f7.jpg",
                            Name = "Dream Delux Ramsäng, enkelsäng med bäddmadrass Sense Delux",
                            Price = 10495m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 10,
                            Description = "Med sin följsamma och omfamnande känsla blir Dream en självklar favorit i många år framöver. Det som skapar den mysiga känslan är en X-pocketresår i samarbete med en 5-zons pocketresår i den övre resårkärnan. Sängens övre pocketresår ger en helt individuell avlastning vilket minskar risken för tryck som gör att du vaknar och X-pocketresåren ger madrassen en extra ytmjuk känsla som bidrar till den omfamnande känslan. För en extra stabilitet i sängen har vi lagt till en kantförstärkning i övre resårkärnan. Den undre resårkärnan har en pocketresår som gör att du får ett extra djup i sängen och mycket god följsamhet. Sängen är svensktillverkad och finns i tre olika komforter, medium, fast eller extra fast. I priset ingår bäddmadrass Sense Delux och metallben.",
                            ImageUrl = "/images/products/be42c2c5-bc3c-4c14-a959-e100bdb9eeab_188.jpg",
                            Name = "Dream Delux Ramsäng, enkelsäng med bäddmadrass Sense Delux",
                            Price = 10495m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 11,
                            Description = "Bordlampa med LED-belysning och dimmer. Ljuskälla ingår. Cato LED ingår i en serie. Endast för inomhusbruk, kan ej användas i våtrum.",
                            ImageUrl = "/images/products/12337.jpg0",
                            Name = "Cato LED Bordslampa",
                            Price = 1871.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 12,
                            Description = "Vägglampa med LED-belysning och dimmer. Finns i flera olika utföranden.  Ljuskälla ingår. Cato LED ingår i en serie. Endast för inomhusbruk, kan ej användas i våtrum.",
                            ImageUrl = "/images/products/12173.jpg",
                            Name = "Cato LED Vägglampa",
                            Price = 1346.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 13,
                            Description = "Bordlampa med LED-belysning och dimmer. Ljuskälla ingår. Cato LED ingår i en serie. Endast för inomhusbruk, kan ej användas i våtrum.",
                            ImageUrl = "/images/products/12339.jpg",
                            Name = "Cato LED Bordslampa",
                            Price = 2471.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 14,
                            Description = "Tidlös golvlampa i metall med riktbar ljuskälla, anpassad för LED-lampa för lång brinntid.  Bra lampa för läsning. Ljuskälla LED 3x1 W ingår. Cato LED ingår i en serie. Endast för inomhusbruk, kan ej användas i våtrum.",
                            ImageUrl = "/images/products/11973.jpg",
                            Name = "Cato LED Golvlampa",
                            Price = 2471.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 15,
                            Description = "Bordlampa med LED-belysning och dimmer. Ljuskälla ingår. Cato LED ingår i en serie. Endast för inomhusbruk, kan ej användas i våtrum.",
                            ImageUrl = "/images/products/12340.jpg",
                            Name = "Cato LED Bordslampa",
                            Price = 1871.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 16,
                            Description = "Timeout är en unik fåtölj som är skräddarsydd just för dig. Fåtöljen har ett höj och sänkbart nackstöd samt en ledad rygg som följer ryggens form när du lutar dig tillbaka. Detta ger en maximal avlastning och ergonomisk vila i alla lägen vilket ökar blodcirkulationen. Du sätter själv din prägel på fåtöljens uttryck genom att bestämma klädsel och underrede. Välj mellan 300 olika läder, tyger och färger. Med 10 års garanti på stomme, sits och rygg blir fåtöljen än mer unik. Du kan även komplettera din fåtölj med en matchande fotpall.",
                            ImageUrl = "/images/products/20820.jpg",
                            Name = "Timeout Fåtölj",
                            Price = 14246.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 17,
                            Description = "Fotpallens vinkel passar fåtöljen Timeouts alla positioner, så att du får ett naturligt stöd oavsett längd. Du sätter själv din prägel på fåtöljen och fotpallens uttryck genom att bestämma klädsel och underrede. Välj mellan 300 olika läder, tyger och färger. Med 10 års garanti blir din Timeout än mer unik.",
                            ImageUrl = "/images/products/22501.jpg",
                            Name = "Timeout Fotpall",
                            Price = 3896.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 18,
                            Description = "Timeout är en unik fåtölj som är skräddarsydd just för dig. Fåtöljen har ett höj och sänkbart nackstöd samt en ledad rygg som följer ryggens form när du lutar dig tillbaka. Detta ger en maximal avlastning och ergonomisk vila i alla lägen vilket ökar blodcirkulationen. Du sätter själv din prägel på fåtöljens uttryck genom att bestämma klädsel och underrede. Välj mellan 300 olika läder, tyger och färger. Med 10 års garanti på stomme, sits och rygg blir fåtöljen än mer unik. Du kan även komplettera din fåtölj med en matchande fotpall.",
                            ImageUrl = "/images/products/20798.jpg",
                            Name = "Timeout Fåtölj",
                            Price = 14246.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 19,
                            Description = "Fotpallens vinkel passar fåtöljen Timeouts alla positioner, så att du får ett naturligt stöd oavsett längd. Du sätter själv din prägel på fåtöljen och fotpallens uttryck genom att bestämma klädsel och underrede. Välj mellan 300 olika läder, tyger och färger. Med 10 års garanti blir din Timeout än mer unik.",
                            ImageUrl = "/images/products/22336.jpg",
                            Name = "Timeout Fotpall",
                            Price = 3896.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 20,
                            Description = "Svensktillverkad fotpall som går att få i flera olika utföranden. Kompletteras till Life fåtölj.",
                            ImageUrl = "/images/products/92990.jpg00",
                            Name = "Life Fotpall",
                            Price = 3483.75m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 21,
                            Description = "Mjuk och lyxig matta i slitstark polyester som inte luddar. Trådarna i mattan varierar i nyans och lyster som ger mattan liv och ger rummet en trivsam och behaglig känsla. Fackmässig plantvätt.",
                            Name = "Madison Ryamatta",
                            Price = 2395m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 22,
                            Description = "Mjuk och lyxig matta i slitstark polyester som inte luddar. Trådarna i mattan varierar i nyans och lyster som ger mattan liv och ger rummet en trivsam och behaglig känsla. Fackmässig plantvätt.",
                            ImageUrl = "/images/products/192.jpg",
                            Name = "Madison Ryamatta",
                            Price = 2395m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 23,
                            Description = "Fotpallens vinkel passar fåtöljen Timeouts alla positioner, så att du får ett naturligt stöd oavsett längd. Du sätter själv din prägel på fåtöljen och fotpallens uttryck genom att bestämma klädsel och underrede. Välj mellan 300 olika läder, tyger och färger.",
                            ImageUrl = "/images/products/40603.jpg",
                            Name = "Timeout Fotpall",
                            Price = 2696.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 24,
                            Description = "Timeout är en unik fåtölj som är skräddarsydd just för dig. Fåtöljen har ett höj och sänkbart nackstöd samt en ledad rygg som följer ryggens form när du lutar dig tillbaka. Detta ger en maximal avlastning och ergonomisk vila i alla lägen vilket ökar blodcirkulationen. Du sätter själv din prägel på fåtöljens uttryck genom att bestämma klädsel och underrede. Välj mellan 300 olika läder, tyger och färger. Med 10 års garanti på stomme, sits och rygg blir fåtöljen än mer unik. Du kan även komplettera din fåtölj med en matchande fotpall.",
                            ImageUrl = "/images/products/40602.jpg",
                            Name = "Timeout Fåtölj",
                            Price = 9746.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 25,
                            Description = "Timeout är en unik recliner som är skräddarsydd just för dig. Reclinerfåtöljen har ett höj och sänkbart nackstöd samt en ledad rygg som följer ryggens form när du lutar dig tillbaka. Detta ger en maximal avlastning och ergonomisk vila i alla lägen vilket ökar blodcirkulationen. Du sätter själv din prägel på fåtöljens uttryck genom att bestämma klädsel och underrede. Välj mellan 300 olika läder, tyger och färger. Med 10 års garanti på stomme, sits och rygg blir din recliner än mer unik. Timeout finns även som fåtölj och fotpall.",
                            ImageUrl = "/images/products/20836.jpg",
                            Name = "Timeout Recliner",
                            Price = 14621.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 26,
                            Description = "Cord matbord är i lackerat ekfaner med dekorativa ribbor. Leon är en klädd stol med lätt vadderad dyna och ben i lackerad metall.",
                            ImageUrl = "/images/products/118413.jpg",
                            Name = "Cord Matgrupp med 4 stolar Leon",
                            Price = 13495m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 27,
                            Description = "Wilma matbord är ett riktigt genuint svenskt hantverk där materialen noga väljs ut av erfarna snickare, anpassas och sätts ihop för hand. Matbordet är tillverkat i björk och mdf som sedan handmålas i vit lasyr med pensel för att få den djupa och levande känslan av genuint hantverk. Bordsskivan finns i flera utföranden och är kan förlängas med 2 st tilläggsskivor, à 50 cm.",
                            ImageUrl = "/images/products/122785.jpg0",
                            Name = "Wilma Matgrupp med 6 stolar",
                            Price = 29995m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 28,
                            Description = "Sittbänk med stoppad pikerad topp, som blir en fin detalj till sängen och erbjuder praktisk förvaring i sovrummet. Perfekt för att förvara ett extra täcke och kudde eller annat som du behöver stoppa undan. Bänken kommer i tyg Noa eller sammetstyg Macy. I priset ingår 112 cm ben.",
                            ImageUrl = "/images/products/6ce072_258571_a025b7_76f7b4_faef9d_74fd29_cf7132_db3f64_204a46_06b.jpg",
                            Name = "Energy Sittbänk",
                            Price = 6495m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 29,
                            Description = "Wilma matbord är ett riktigt genuint svenskt hantverk där materialen noga väljs ut av erfarna snickare, anpassas och sätts ihop för hand. Matbordet är tillverkat i björk och mdf som sedan handmålas i vit lasyr med pensel för att få den djupa och levande känslan av genuint hantverk. Bordsskivan finns i flera utföranden och är kan förlängas med 2 st tilläggsskivor, à 50 cm.",
                            ImageUrl = "/images/products/50009.jpg",
                            Name = "Wilma Matgrupp med 6 stolar",
                            Price = 35795m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 30,
                            Description = "Sov gott och vakna upp utvilad i Energy. Den svensktillverkade sängserien består av noga utvalda komponenter som bidrar till den höga komforten. Fjädrarna i Energy är konvexa och optimalt förspända som innebär att ett maximalt stöd uppnås. Pocketkärnan är uppdelad i 3 zoner som är utformade för att ge individuell fjädring för mycket god tryckavlastning och följsamhet. Sängens undre kärna är uppbyggd med en fast pocketkärna, 13 cm hög. En 8 cm hög träram finns längst ner på sängen för en stadig bas. På toppen ligger bäddmadrassen som är stoppad med soft skum. Välj mellan komforten medium, fast eller extra fast och finns i sammets- eller möbeltygsklädsel. Madrassen i mitten består av två kassetter som läggs i ett tygfodral.",
                            ImageUrl = "/images/products/6ce072_e1526e_a025b7_50c9db_faef9d_d3e1e1_cf7132_db3f64_4a1e02_2a9.jpg",
                            Name = "Energy Kontinentalsäng, dubbelsäng med bäddmadrass Energy",
                            Price = 28995m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 31,
                            Description = "Lucas är ett matbord i tåligt laminat med underrede i lackerat trä. Laminat står sig bättre emot repor och vätskor jämfört med en lackad yta. Einar är en traditionell pinnstol i massivt trä med en lackerad yta.",
                            ImageUrl = "/images/products/105849.jpg",
                            Name = "Lucas Matgrupp med 4 stolar Einar",
                            Price = 6795m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 32,
                            Description = "Sharp är ett bord i laminat som är extra tålig och mer beständig mot repor och vätskor. Benen är i lackerad metall.",
                            ImageUrl = "/images/products/103023.jpg",
                            Name = "Sharp Matbord, Ø 110 cm",
                            Price = 3095m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 33,
                            Description = "Wilma matbord är ett riktigt genuint svenskt hantverk där materialen noga väljs ut av erfarna snickare, anpassas och sätts ihop för hand. Matbordet är tillverkat i björk och mdf som sedan handmålas i vit lasyr med pensel för att få den djupa och levande känslan av genuint hantverk. Bordsskivan finns i flera utföranden och är kan förlängas med 2 st tilläggsskivor, à 50 cm.",
                            ImageUrl = "/images/products0/50307.jpg",
                            Name = "Wilma Matgrupp med 6 stolar",
                            Price = 35795m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 34,
                            Description = "En karaktäristisk takpendel som med sina skira glaskupor ger ett mjukt men ändå vågat uttryck. Men Grapes är inte bara attityd, när ljuset silas genom de tonade glaset bildas ett mjukt och stämningsfullt ljus i rummet. Köp gärna till någon av våra passande ljuskällor.",
                            ImageUrl = "/images/products/42763.jpg",
                            Name = "Grapes Taklampa",
                            Price = 2246.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 35,
                            Description = "Stilren handvävd ullmatta med läderkant. Ullen gör mattan naturligt smutsavvisande och slitstark. Då mattan är handvävd samt att läderkanten är påsydd för hand, är varje matta unik. Skarvar kan även förekomma på läderkanten. Grimsby är en lättmatchad och snygg matta som också är vändbar vilket ger den en lång livslängd. Köp gärna till vårt mattunderlägg. Kemtvätt.",
                            ImageUrl = "/images/products/69941.jpg",
                            Name = "Grimsby Ullmatta",
                            Price = 1046.25m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 36,
                            Description = "Mjuk och härlig lammskinnsfäll som blir en dekorativ detalj i soffan eller hängandes över en stolsrygg. Använd en lätt fuktad tvättsvamp eller klädvårdsrulle över ytan för att samla ihop eventuellt damm och smuts. ",
                            ImageUrl = "/images/products/56449.jpg",
                            Name = "Isak Lammskinn",
                            Price = 349m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 37,
                            Description = "Ullrika är en len och värmande fårskinnsdyna. Använd en lätt fuktad tvättsvamp eller klädvårdsrulle över ytan för att samla ihop eventuellt damm och smuts.",
                            ImageUrl = "/images/products/94429.jpg",
                            Name = "Ulrika Stolsdyna, Ø 34 cm",
                            Price = 99m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 38,
                            Description = "Ritz är en serie badtextil med exklusiv hotellkänsla, tillverkad med ett så kallat Air rich-framtagande. Air rich innebär att handduken är vävd i 100% bomull tillsammans med vattenlösliga fibrer. I slutprocessen sköljs de överflödiga fibrerna bort vilket ger en luftig och mycket mjuk handduk, tvätt efter tvätt. Dessutom är handdukarna Oeko-Tex certifierade och är därmed extra snälla mot din hud och miljön. Ritz tvättas enkelt i 60°C maskintvätt.",
                            ImageUrl = "/images/products/85822.jpg",
                            Name = "Ritz Badlakan, 90x150 cm",
                            Price = 499m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 39,
                            Description = "Mjuk badrock i bomullsvelour. Ritz har stort slag vid ärmslut, vida ärmar och två fickor fram. Badrocken stängs med knytband i midjan.\r\nLängd: 130 cm,\r\nArmlängd: 54 cm,\r\nBredd över axlar: 61 cm,\r\nBredd över bröstet: 63,5 cm,\r\nLängd knytband: 203 cm",
                            ImageUrl = "/images/products/138182.jpg",
                            Name = "Ritz Badrock, L/XL",
                            Price = 999m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 40,
                            Description = "Fårskinnstofflor som går att använda året om då de är gjorda i ett naturligt material. Ullen har bland annat temperaturreglerande egenskaper som gör att de håller dina fötter svala under varma dagar och skänker värme när det är kallt. Är du en person som har besvär med kalla fötter så är detta ett bra alternativ, som dessutom är fina att titta på. Tofflorna finns i storlek 42-43 och 44-45.",
                            ImageUrl = "/images/product00s/144495.jpg",
                            Name = "Trysil Tofflor, fårskinn kastanj/vit, 1 par",
                            Price = 399m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 41,
                            Description = "Sannäs är ett härligt täcke med fyllning av microfiber och hålfiber, yttertyg i 100% bomullscambric. Hålfibern innehåller luft som i sin tur är en bra isolering och transporterar effektivt bort fukt från kroppen som bidrar till bättre sovklimat och komfort. För din och miljöns skull är Sannäs OEKO-TEX®-certifierad produkt Tvättas i 60°C och torktumlas på låg värme.",
                            ImageUrl = "/images/products/47062.jpg",
                            Name = "Sannäs Fibertäcke, 230x220 cm, svalt",
                            Price = 899m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 42,
                            Description = "Meja är en pläd i mjuk och skön pälsimitation. Pläden är tillverkad i 100% polyester, OEKO-TEX®-certifierad produkt och kan tvättas i 30°C skontvätt.",
                            ImageUrl = "/images/products/129580.jpg",
                            Name = "Meja Pläd, 130x170 cm",
                            Price = 599m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 43,
                            Description = "Din kropp alstrar sin egen värme. Så om du svettas eller fryser beror både på vem just du är och på temperaturen i rummet, Cecilia från EngmoDun finns i flera varianter beroende på hur svalt eller varmt du vill ha ditt täcke. Naturmaterial andas och håller kvar lagom mycket värme, men släpper igenom överskottet.\r\n\r\nCecilia kuddar och täcken är fyllt med naturligt, nästan viktlöst finaste mysk anddun för att ge den optimala sovkomforten. Maskintvätt 60 °C. med ett skonsamt tvättmedel, och torka i torktumlare. Skaka om täcket eller kudden och känn efter om det känns torrt och doftar friskt, då är det klart att användas igen. Vädra och lufta gärna ditt täcke ofta för att bibehålla den luftiga och lätta känslan. Täcket levereras i en fin tygpåse, tänk på att det legat rullpackad och kan behöva någon dag på sig att återfå sin form.",
                            ImageUrl = "/images/products/109470.jpg",
                            Name = "EngmoDun Cecilia Duntäcke, 150x210 cm, varmt",
                            Price = 2795m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 44,
                            Description = "Färgstarka motiv med en personlig karaktär är det som kännetecknar konstnären Carolina Gynnings verk. Varje motiv förmedlar ett eget budskap med inspiration från livets pågående skeenden. Vinglaset finns med flera motiv som är fina att duka med tillsammans.",
                            ImageUrl = "/images/products/42860.jpg",
                            Name = "Carolina Gynning Rödvinsglas, 75 cl",
                            Price = 269m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 45,
                            Description = "Daga är ett dricksglas inspirerad av vardagen där funktionalitet och enkelhet möts. Vattenglaset i randigt klarglas blir snabbt en favorit med sin behändiga storlek och stilrena design. Glasen är dessutom stapelbara och tar därför inte mycket plats när de inte används.",
                            ImageUrl = "/images/products/70063.jpg",
                            Name = "Daga Glas, 4-pack, 25,5 cl",
                            Price = 0m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 46,
                            Description = "Vilgot är en möbelserie i retroinspirerad skandinavisk stil. Detaljerna med lätt utställda ben och raka former är det som sätter prägeln för serien. Matbordet är förberett för att kompletteras med två tilläggsskivor à 45 cm. Tilläggsskiva säljs separat.",
                            ImageUrl = "/images/products/118907.jpg",
                            Name = "Vilgot Matbord, L 200 cm",
                            Price = 7995m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 47,
                            Description = "Exklusiv sovkudde med spänstig bollfiber som gör att kudden håller sin form under natten och ger ett effektivt stöd under sömnen. Kudden är omsluten av yttertyg i 100% bomullscambric.",
                            ImageUrl = "/images/products/135197.jpg",
                            Name = "Höie Dreamnight Fiberkudde, 50x60 cm, mellan",
                            Price = 174m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 48,
                            Description = "Denna klassiska kudde är tillverkad i ett speciellt utvecklat Tempur extra soft-material för att erbjuda en fin balans mellan mjukhet och stöd. Den är perfekt för dig som vill ha det stöd som Tempur erbjuder, med en mjukare kramgo känsla. Formad som en traditionell kudde, passar den de flesta sovställningar. Fodralet kan maskintvättas i 40°C.",
                            ImageUrl = "/images/products/6290.jpg",
                            Name = "Tempur Cloud Funktionskudde, 50x60 cm, mjuk",
                            Price = 2195m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 49,
                            Description = "Särö är en klädd sänggavel i välvd modell som blir ett fint komplement till din Särö säng. Den är klädd i ett slitstarkt tyg med möbelkänsla som ger en ombonad känsla i sovrummet. Sänggaveln är mjuk och skön att luta sig mot när du vill sitta i sängen och läsa eller se på TV. Till sänggaveln ingår ben, höjd 12 cm. Totalhöjd på gavel med ben är 149 cm.",
                            ImageUrl = "/images/products/130205.jpg",
                            Name = "Särö välvd Sänggavel, B 160-210 cm",
                            Price = 8995m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 50,
                            Description = "Särö är en klädd sänggavel i pikerad modell som blir ett fint komplement till din Särö säng. Den är klädd i ett slitstarkt tyg med möbelkänsla som ger en ombonad känsla i sovrummet. Sänggaveln är mjuk och skön att luta sig mot när du vill sitta i sängen och läsa eller se på TV. Till sänggaveln ingår ben, höjd 12 cm. Totalhöjd på gavel med ben är 137cm.",
                            ImageUrl = "/images/products/130100.jpg",
                            Name = "Särö pikerad L Sänggavel, B 90-120 cm",
                            Price = 7995m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 51,
                            Description = "Luca är en hatthylla i lackerad metall med utmärkande detaljer och tre praktiska krokar. Kombinera gärna med andra delar i serien för att få till en enhetlig klädförvaring.",
                            ImageUrl = "/images/products/69359.jpg",
                            Name = "Luca Hatthylla, B 70 cm",
                            Price = 899m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 52,
                            Description = "Magaluf är ett stilsäkert runt matbord i konstrotting av god kvalitet. Bordet har en stomme i aluminium och konstrotting och en skiva i konstträ. Bordet är både underhållsfritt och tåligt. Alla våra flätade utemöbler är handgjorda och gör varje möbel unik i utseende och färg. Ta hand om dina möbler så håller de längre, se dokument för skötselråd för produkten.",
                            ImageUrl = "/images/products/68194.jpg",
                            Name = "Magaluf Utebord, Ø 150 cm",
                            Price = -6995m,
                            Stock = 999
                        });
                });

            modelBuilder.Entity("KodtestMio.DbModel.EntityModels.OrderItem", b =>
                {
                    b.HasOne("KodtestMio.DbModel.EntityModels.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KodtestMio.DbModel.EntityModels.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
